import { serve } from "bun";
import { renderToString } from "react-dom/server";
import { App } from "./App";
import React from "react";
import path from "node:path";

// Build the client-side assets with sourcemaps
// We use naming to keep asset names predictable for simple SSR matching
await Bun.build({
  entrypoints: ["./src/index.html"],
  outdir: "./dist",
  sourcemap: "external",
  target: "browser",
  naming: {
    asset: "[name].[ext]",
  }
});

const server = serve({
  routes: {
    "/ssr": async () => {
      const appHtml = renderToString(<App />);
      const html = await Bun.file("./dist/index.html").text();
      
      // Inject the rendered app into the HTML
      let ssrHtml = html.replace(
        '<div id="root"></div>',
        `<div id="root">${appHtml}</div>`
      );

      // Fix absolute paths for assets generated by Bun's server-side loader
      // Bun's SSR will use absolute paths for imported assets (like SVGs)
      // We convert them to relative paths to match the bundled output
      const projectSrcPath = path.join(import.meta.dir, "src");
      ssrHtml = ssrHtml.replaceAll(projectSrcPath + "/", "./");
      // Also handle the case where it might be just the project dir
      ssrHtml = ssrHtml.replaceAll(import.meta.dir + "/", "./");

      return new Response(ssrHtml, {
        headers: { "Content-Type": "text/html" },
      });
    },

    "/api/hello": {
      async GET(req) {
        return Response.json({
          message: "Hello, world!",
          method: "GET",
        });
      },
      async PUT(req) {
        return Response.json({
          message: "Hello, world!",
          method: "PUT",
        });
      },
    },

    "/api/hello/:name": async (req) => {
      const name = req.params.name;
      return Response.json({
        message: `Hello, ${name}!`,
      });
    },

    // Serve static files and fallback to index.html for SPA
    "/*": async (req) => {
      const url = new URL(req.url);
      const pathname = url.pathname === "/" ? "/index.html" : url.pathname;
      const file = Bun.file(`./dist${pathname}`);
      
      if (await file.exists()) {
        return new Response(file);
      }
      
      // Fallback for SPA: serve the original index.html (not SSR)
      return new Response(Bun.file("./dist/index.html"));
    },
  },

  development: process.env.NODE_ENV !== "production" && {
    hmr: true,
    console: true,
  },
});

console.log(`🚀 Server running at ${server.url}`);
console.log(`🔗 SSR available at ${server.url}ssr`);