import { serve } from "bun";
import { renderToString } from "react-dom/server";
import { App } from "./App";
import React from "react";
import index from "./index.html";

const server = serve({
  routes: {
    "/ssr": async (req) => {
      const appHtml = renderToString(<App />);

      // Fetch the root HTML from our own server to get the bundled/transformed version.
      // Global fetch() is the most reliable way to capture the HMR scripts and hashed paths
      // while keeping the code simple and using Bun's native features.
      const response = await fetch(server.url);
      const html = await response.text();

      // Inject the rendered app into the HTML
      let ssrHtml = html.replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`);

      // Fix absolute paths for assets generated by Bun's server-side loader
      const projectSrcPath = import.meta.dir + "/src/";
      ssrHtml = ssrHtml.replaceAll(projectSrcPath, "./src/");
      ssrHtml = ssrHtml.replaceAll(import.meta.dir + "/", "./");

      return new Response(ssrHtml, {
        headers: { "Content-Type": "text/html" },
      });
    },

    "/api/hello": {
      async GET(req) {
        return Response.json({ message: "Hello, world!", method: "GET" });
      },
      async PUT(req) {
        return Response.json({ message: "Hello, world!", method: "PUT" });
      },
    },

    "/api/hello/:name": async (req) => {
      const name = req.params.name;
      return Response.json({ message: `Hello, ${name}!` });
    },

    // Catch-all route to serve the SPA and its assets (scripts, images, etc.)
    "/*": index,
  },

  development: process.env.NODE_ENV !== "production" && {
    hmr: true,
    console: true,
  },
});

console.log(`🚀 Server running at ${server.url}`);
console.log(`🔗 SSR available at ${server.url}ssr`);
